<?php
session_start();
require_once __DIR__ . '/../../config/database.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Both operations require the location ID
    $locationid = $_POST['locationid'] ?? null; 
    
    // Check if the form submission is for an 'update' or a 'delete' action
    $action = $_POST['action'] ?? 'update'; 

    if (!$locationid) {
        die("Error: Location ID is required.");
    }

    // =======================================================
    // 🗑️ WORKFLOW A: DELETE OPERATION (CRUD - Delete)
    // =======================================================
    if ($action === 'delete') {
        try {
            $pdo->beginTransaction();

            // Step 1: Delete from child/dependent tables first to prevent Foreign Key constraint violations
            $sqlDeleteImg = "DELETE FROM image_loc WHERE locationid = :locid";
            $stmtImg = $pdo->prepare($sqlDeleteImg);
            $stmtImg->execute(['locid' => $locationid]);

            $sqlDeleteAnalysis = "DELETE FROM generated_analysis WHERE locationid = :locid";
            $stmtAnalysis = $pdo->prepare($sqlDeleteAnalysis);
            $stmtAnalysis->execute(['locid' => $locationid]);

            $sqlDeleteReport = "DELETE FROM report WHERE locationid = :locid";
            $stmtReport = $pdo->prepare($sqlDeleteReport);
            $stmtReport->execute(['locid' => $locationid]);

            // Step 2: Delete the physical parent record from the location table last
            $sqlDeleteLoc = "DELETE FROM location WHERE locationid = :locid";
            $stmtLoc = $pdo->prepare($sqlDeleteLoc);
            $stmtLoc->execute(['locid' => $locationid]);

            $pdo->commit();
            header("Location: /logic/controller/managereport.php");
            exit();

        } catch (Exception $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }
            die("Error deleting report: " . $e->getMessage());
        }
    }

    // =======================================================
    // 📝 WORKFLOW B: UPDATE OPERATION (CRUD - Update)
    // =======================================================
    else if ($action === 'update') {
        // Collect update form data
        $status_update = $_POST['status_update'] ?? null;
        $erosion_risk  = $_POST['erosion_risk'] ?? null; // For generated_analysis
        $action_taken  = $_POST['action_taken'] ?? null;
        
        // Optional attributes for your analytical module
        $suitability_score = $_POST['suitability_score'] ?? null; 
        $prediction_memo   = $_POST['prediction_memo'] ?? null;  

        if (!$status_update || !$action_taken || !$erosion_risk) {
            die("Error: Missing required form fields for update execution.");
        }

        try {
            $pdo->beginTransaction();

            // Step 1: Insert the operational action into the authorities table
            $sqlAuth = "INSERT INTO authorities (status_update, action_taken) 
                        VALUES (:status, :action) RETURNING authoritiesid";
            
            $stmtAuth = $pdo->prepare($sqlAuth);
            $stmtAuth->execute([
                'status' => $status_update,
                'action' => $action_taken
            ]);
            
            // Get the ID generated by SERIAL
            $newAuthID = $stmtAuth->fetchColumn();

            // Step 2: Link the report row to this new authority action
            $sqlReport = "UPDATE report 
                          SET authoritiesid = :authid 
                          WHERE locationid = :locid";
            
            $stmtReport = $pdo->prepare($sqlReport);
            $stmtReport->execute([
                'authid' => $newAuthID,
                'locid'  => $locationid
            ]);

            // Step 3: Manage the scientific metrics inside the new generated_analysis table (Upsert logic)
            $sqlCheck = "SELECT analysisid FROM generated_analysis WHERE locationid = :locid";
            $stmtCheck = $pdo->prepare($sqlCheck);
            $stmtCheck->execute(['locid' => $locationid]);
            $existingAnalysisID = $stmtCheck->fetchColumn();

            if ($existingAnalysisID) {
                // Update existing analysis parameters
                $sqlAnalysis = "UPDATE generated_analysis 
                                SET erosion_risk = :risk, 
                                    suitability_score = :suit, 
                                    prediction_memo = :memo,
                                    anaysis_update = NOW() 
                                WHERE locationid = :locid";
            } else {
                // Insert brand new analytical calculation profile
                $sqlAnalysis = "INSERT INTO generated_analysis (locationid, erosion_risk, suitability_score, prediction_memo) 
                                VALUES (:locid, :risk, :suit, :memo)";
            }

            $stmtAnalysis = $pdo->prepare($sqlAnalysis);
            $stmtAnalysis->execute([
                'locid' => $locationid,
                'risk'  => $erosion_risk,
                'suit'  => $suitability_score,
                'memo'  => $prediction_memo
            ]);

            $pdo->commit();
            header("Location: /logic/controller/managereport.php");
            exit();

        } catch (Exception $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }
            die("Error updating report: " . $e->getMessage());
        }
    }
}